"""Initial migration with all models.

Revision ID: 7f25595d4099
Revises:
Create Date: 2025-12-15 08:56:38.312974

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f25595d4099"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_models_id"), "llm_models", ["id"], unique=False)
    op.create_index(op.f("ix_llm_models_name"), "llm_models", ["name"], unique=False)
    op.create_table(
        "provider_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("avg_latency_ms", sa.Float(), nullable=True),
        sa.Column("error_rate", sa.Float(), nullable=True),
        sa.Column("circuit_state", sa.String(length=20), nullable=True),
        sa.Column("circuit_opened_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=True),
        sa.Column("last_health_check", sa.DateTime(), nullable=True),
        sa.Column("last_successful_request", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_index(
        "idx_provider_status_available",
        "provider_status",
        ["is_available"],
        unique=False,
    )
    op.create_index("idx_provider_status_provider", "provider_status", ["provider"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_api_key_hash", "users", ["api_key_hash"], unique=False)
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_api_key_hash"), "users", ["api_key_hash"], unique=True)
    op.create_table(
        "evasion_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("target_model_id", sa.Integer(), nullable=False),
        sa.Column("initial_prompt", sa.String(), nullable=False),
        sa.Column("strategy_chain", sa.JSON(), nullable=False),
        sa.Column("success_criteria", sa.String(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("final_status", sa.String(), nullable=True),
        sa.Column("overall_success", sa.Boolean(), nullable=True),
        sa.Column("failed_reason", sa.String(), nullable=True),
        sa.Column("results", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["target_model_id"],
            ["llm_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evasion_tasks_id"), "evasion_tasks", ["id"], unique=False)
    op.create_index(op.f("ix_evasion_tasks_task_id"), "evasion_tasks", ["task_id"], unique=True)
    op.create_table(
        "model_selection_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("previous_provider", sa.String(length=50), nullable=True),
        sa.Column("previous_model", sa.String(length=100), nullable=True),
        sa.Column("new_provider", sa.String(length=50), nullable=False),
        sa.Column("new_model", sa.String(length=100), nullable=False),
        sa.Column("change_reason", sa.String(length=50), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_history_created_at",
        "model_selection_history",
        ["created_at"],
        unique=False,
    )
    op.create_index("idx_history_user_id", "model_selection_history", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_model_selection_history_created_at"),
        "model_selection_history",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "model_usage_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("estimated_cost_cents", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index("idx_usage_created_at", "model_usage_records", ["created_at"], unique=False)
    op.create_index(
        "idx_usage_provider_model",
        "model_usage_records",
        ["provider", "model"],
        unique=False,
    )
    op.create_index("idx_usage_request_id", "model_usage_records", ["request_id"], unique=False)
    op.create_index("idx_usage_user_id", "model_usage_records", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_model_usage_records_created_at"),
        "model_usage_records",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "rate_limit_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_size_seconds", sa.Integer(), nullable=True),
        sa.Column("request_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("max_requests_per_window", sa.Integer(), nullable=True),
        sa.Column("max_tokens_per_window", sa.Integer(), nullable=True),
        sa.Column("is_limited", sa.Boolean(), nullable=True),
        sa.Column("limited_until", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "provider",
            "model",
            name="uq_rate_limit_user_provider_model",
        ),
    )
    op.create_index(
        "idx_rate_limit_user_provider",
        "rate_limit_records",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_index("idx_rate_limit_window", "rate_limit_records", ["window_start"], unique=False)
    op.create_table(
        "user_model_preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("selected_provider", sa.String(length=50), nullable=False),
        sa.Column("selected_model", sa.String(length=100), nullable=False),
        sa.Column("fallback_provider", sa.String(length=50), nullable=True),
        sa.Column("fallback_model", sa.String(length=100), nullable=True),
        sa.Column("model_settings", sa.JSON(), nullable=True),
        sa.Column("remember_selection", sa.Boolean(), nullable=True),
        sa.Column("auto_fallback", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "idx_preferences_provider",
        "user_model_preferences",
        ["selected_provider"],
        unique=False,
    )
    op.create_index("idx_preferences_user_id", "user_model_preferences", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_preferences_user_id", table_name="user_model_preferences")
    op.drop_index("idx_preferences_provider", table_name="user_model_preferences")
    op.drop_table("user_model_preferences")
    op.drop_index("idx_rate_limit_window", table_name="rate_limit_records")
    op.drop_index("idx_rate_limit_user_provider", table_name="rate_limit_records")
    op.drop_table("rate_limit_records")
    op.drop_index(op.f("ix_model_usage_records_created_at"), table_name="model_usage_records")
    op.drop_index("idx_usage_user_id", table_name="model_usage_records")
    op.drop_index("idx_usage_request_id", table_name="model_usage_records")
    op.drop_index("idx_usage_provider_model", table_name="model_usage_records")
    op.drop_index("idx_usage_created_at", table_name="model_usage_records")
    op.drop_table("model_usage_records")
    op.drop_index(
        op.f("ix_model_selection_history_created_at"),
        table_name="model_selection_history",
    )
    op.drop_index("idx_history_user_id", table_name="model_selection_history")
    op.drop_index("idx_history_created_at", table_name="model_selection_history")
    op.drop_table("model_selection_history")
    op.drop_index(op.f("ix_evasion_tasks_task_id"), table_name="evasion_tasks")
    op.drop_index(op.f("ix_evasion_tasks_id"), table_name="evasion_tasks")
    op.drop_table("evasion_tasks")
    op.drop_index(op.f("ix_users_api_key_hash"), table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_api_key_hash", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_provider_status_provider", table_name="provider_status")
    op.drop_index("idx_provider_status_available", table_name="provider_status")
    op.drop_table("provider_status")
    op.drop_index(op.f("ix_llm_models_name"), table_name="llm_models")
    op.drop_index(op.f("ix_llm_models_id"), table_name="llm_models")
    op.drop_table("llm_models")
    # ### end Alembic commands ###
