export const TECHNIQUE_SUITES = [
    { value: "basic", label: "Basic", description: "Simple transformations", category: "Basic" },
    { value: "standard", label: "Standard", description: "Balanced approach", category: "Basic" },
    { value: "advanced", label: "Advanced", description: "Complex multi-layer", category: "Basic" },
    { value: "expert", label: "Expert", description: "Maximum sophistication", category: "Basic" },
    { value: "quantum", label: "Quantum", description: "Quantum-inspired bypass", category: "Quantum" },
    { value: "quantum_exploit", label: "Quantum Exploit", description: "Advanced quantum techniques", category: "Quantum" },
    { value: "universal_bypass", label: "Universal Bypass", description: "Multi-vector approach", category: "Bypass" },
    { value: "chaos_ultimate", label: "Chaos Ultimate", description: "Chaotic transformation", category: "Bypass" },
    { value: "mega_chimera", label: "Mega Chimera", description: "Combined techniques", category: "Chimera" },
    { value: "ultimate_chimera", label: "Ultimate Chimera", description: "All techniques combined", category: "Chimera" },
    { value: "autodan", label: "AutoDAN", description: "Automated DAN generation", category: "AutoDAN" },
    { value: "autodan_best_of_n", label: "AutoDAN Best-of-N", description: "Best selection strategy", category: "AutoDAN" },
    { value: "autodan_beam_search", label: "AutoDAN Beam Search", description: "Beam search optimization", category: "AutoDAN" },
    { value: "dan_persona", label: "DAN Persona", description: "Do Anything Now persona", category: "Persona" },
    { value: "roleplay_bypass", label: "Roleplay Bypass", description: "Character-based bypass", category: "Persona" },
    { value: "deep_inception", label: "Deep Inception", description: "Nested context injection", category: "Inception" },
    { value: "cipher", label: "Cipher", description: "Encoding-based bypass", category: "Cipher" },
    { value: "cipher_ascii", label: "Cipher ASCII", description: "ASCII encoding", category: "Cipher" },
    { value: "cipher_caesar", label: "Cipher Caesar", description: "Caesar cipher encoding", category: "Cipher" },
    { value: "cipher_morse", label: "Cipher Morse", description: "Morse code encoding", category: "Cipher" },
    { value: "code_chameleon", label: "Code Chameleon", description: "Code-based obfuscation", category: "Code" },
    { value: "academic_research", label: "Academic Research", description: "Research framing", category: "Persuasion" },
    { value: "subtle_persuasion", label: "Subtle Persuasion", description: "Persuasion techniques", category: "Persuasion" },
    { value: "authority_override", label: "Authority Override", description: "Authority-based bypass", category: "Persuasion" },
    { value: "metamorphic_attack", label: "Metamorphic Attack", description: "Self-modifying prompts", category: "Attack" },
    { value: "payload_splitting", label: "Payload Splitting", description: "Split payload technique", category: "Attack" },
    { value: "cognitive_hacking", label: "Cognitive Hacking", description: "Cognitive manipulation", category: "Attack" },
];

export const TECHNIQUE_CATEGORIES = Array.from(new Set(TECHNIQUE_SUITES.map(t => t.category)));
